name = "LSoundOpt"
uuid = "45ec9002-f63e-4932-b724-fed3823b9cf6"
authors = ["Eduardo Lenz <eduardobarplenz@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
