name = "LSoundOpt"
uuid = "45ec9002-f63e-4932-b724-fed3823b9cf6"
version = "1.0.0-DEV"
authors = ["Eduardo Lenz <eduardobarplenz@gmail.com> and contributors"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LSound = "f73e1f51-bd35-4e1d-877f-2490c5746094"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Lgmsh = "901517f6-ef86-4a80-bf35-2c5b8e720204"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
DelimitedFiles = "1.9.1"
Gmsh = "0.3.1"
HiGHS = "1.20.1"
Ipopt = "1.13.0"
JuMP = "1.29.3"
LSound = "1.0.0"
LaTeXStrings = "1.4.0"
Lgmsh = "1.0.0"
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
ProgressMeter = "1.11.0"
Revise = "3.13.2"
SparseArrays = "1.11.0"
YAML = "0.4.16"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
